# Generated by Django 3.2.9 on 2022-03-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_published',
        ),
    ]
