# Generated by Django 3.2.9 on 2022-03-20 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0003_auto_20220320_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='portfolio/images', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, verbose_name='Адрес ссылки')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Вендоры',
                'verbose_name_plural': 'Вендоры',
            },
        ),
    ]
