# Generated by Django 3.2.9 on 2022-03-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0004_smi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smi',
            options={'verbose_name': 'Сми о нас', 'verbose_name_plural': 'Сми о нас'},
        ),
        migrations.RemoveField(
            model_name='smi',
            name='description',
        ),
        migrations.AlterField(
            model_name='smi',
            name='image',
            field=models.ImageField(upload_to='smi_about/images', verbose_name='Изображение'),
        ),
    ]
