# Generated by Django 3.2.9 on 2022-03-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0006_auto_20220320_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья реестра', 'verbose_name_plural': 'Статья реестра'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория реестра статьи', 'verbose_name_plural': 'Категория реестра статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.CharField(default=True, max_length=100, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=True, max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, verbose_name='Адрес ссылки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='название категории'),
        ),
    ]
