# Generated by Django 3.2.9 on 2022-03-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0008_auto_20220320_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='atricles',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='poisk_hhv_main.category', verbose_name='категория'),
        ),
    ]
