# Generated by Django 3.2.9 on 2022-03-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0012_auto_20220321_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image1',
            field=models.ImageField(upload_to='about_us1/image1', verbose_name='Изображение'),
        ),
    ]
