# Generated by Django 3.2.9 on 2022-03-21 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0013_alter_aboutus_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image1',
            field=models.ImageField(upload_to='about_us/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image2',
            field=models.ImageField(upload_to='about_us/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image3',
            field=models.ImageField(upload_to='about_us/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='poisk_hhv_main.category', verbose_name='категория'),
        ),
    ]
