# Generated by Django 3.2.9 on 2022-03-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0014_auto_20220321_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('url', models.URLField(blank=True, verbose_name='Адрес ссылки')),
            ],
            options={
                'verbose_name': 'Документы о нас ',
                'verbose_name_plural': 'Документы о нас',
            },
        ),
    ]
