# Generated by Django 3.2.9 on 2022-03-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0016_aboutpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('summa', models.CharField(max_length=100, verbose_name='сумма')),
                ('data', models.CharField(max_length=100, verbose_name='дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image1', models.ImageField(upload_to='projects/images', verbose_name='Изображение')),
                ('image2', models.ImageField(upload_to='projects/images', verbose_name='Изображение')),
                ('image3', models.ImageField(upload_to='projects/images', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, verbose_name='Адрес ссылки')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutpartner',
            options={'verbose_name': 'Партнеры о нас ', 'verbose_name_plural': 'Партнеры о нас'},
        ),
    ]
