# Generated by Django 3.2.9 on 2022-03-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0018_auto_20220321_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('group_books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poisk_hhv_main.group_books')),
            ],
        ),
    ]
