# Generated by Django 3.2.9 on 2022-04-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0021_projects_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
    ]
