# Generated by Django 3.2.9 on 2022-06-11 13:35

from django.db import migrations, models
import poisk_hhv_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0023_catimages_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catimages',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AddField(
            model_name='image',
            name='image1',
            field=models.ImageField(default='', upload_to=poisk_hhv_main.models.upload_gallery_image),
        ),
    ]
