# Generated by Django 3.2.9 on 2022-06-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0024_auto_20220611_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image1',
        ),
    ]
