# Generated by Django 3.2.9 on 2022-06-11 13:37

from django.db import migrations, models
import poisk_hhv_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0025_remove_image_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='catimages',
            name='image1',
            field=models.ImageField(default='', upload_to=poisk_hhv_main.models.upload_gallery_image),
        ),
    ]
