# Generated by Django 3.2.9 on 2022-06-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0026_catimages_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catimages',
            name='image1',
            field=models.ImageField(default='', upload_to='cat/images'),
        ),
        migrations.AlterField(
            model_name='catimages',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Описание'),
        ),
    ]
