# Generated by Django 3.2.9 on 2022-06-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0028_auto_20220611_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='catimages',
            name='audio_file',
            field=models.FileField(default='', upload_to='', verbose_name='песенка'),
        ),
    ]
