# Generated by Django 3.2.9 on 2022-06-12 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0031_alter_catimages_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description1', models.TextField(verbose_name='Описание1')),
                ('image1', models.ImageField(upload_to='article/images', verbose_name='Изображение1')),
                ('description2', models.TextField(verbose_name='Описание2')),
                ('image2', models.ImageField(upload_to='article/images', verbose_name='Изображение2')),
                ('description3', models.TextField(verbose_name='Описание3')),
                ('image3', models.ImageField(upload_to='article/images', verbose_name='Изображение3')),
                ('description4', models.TextField(verbose_name='Описание4')),
                ('image4', models.ImageField(upload_to='article/images', verbose_name='Изображение4')),
                ('description5', models.TextField(verbose_name='Описание5')),
                ('image5', models.ImageField(upload_to='article/images', verbose_name='Изображение5')),
                ('description6', models.TextField(verbose_name='Описание6')),
                ('image6', models.ImageField(upload_to='article/images', verbose_name='Изображение6')),
                ('description7', models.TextField(verbose_name='Описание7')),
                ('image7', models.ImageField(upload_to='article/images', verbose_name='Изображение7')),
                ('description8', models.TextField(verbose_name='Описание8')),
                ('image8', models.ImageField(upload_to='article/images', verbose_name='Изображение8')),
                ('description9', models.TextField(verbose_name='Описание9')),
                ('image9', models.ImageField(upload_to='article/images', verbose_name='Изображение9')),
                ('description10', models.TextField(verbose_name='Описание10')),
                ('image10', models.ImageField(upload_to='article/images', verbose_name='Изображение10')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статья',
            },
        ),
    ]
