# Generated by Django 3.2.9 on 2022-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisk_hhv_main', '0032_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description1',
            field=models.TextField(blank=True, null=True, verbose_name='Описание1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description10',
            field=models.TextField(null=True, verbose_name='Описание10'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description2',
            field=models.TextField(null=True, verbose_name='Описание2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description3',
            field=models.TextField(null=True, verbose_name='Описание3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description4',
            field=models.TextField(null=True, verbose_name='Описание4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description5',
            field=models.TextField(null=True, verbose_name='Описание5'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description6',
            field=models.TextField(null=True, verbose_name='Описание6'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description7',
            field=models.TextField(null=True, verbose_name='Описание7'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description8',
            field=models.TextField(null=True, verbose_name='Описание8'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description9',
            field=models.TextField(null=True, verbose_name='Описание9'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(null=True, upload_to='article/images', verbose_name='Изображение1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image10',
            field=models.ImageField(null=True, upload_to='article/images', verbose_name='Изображение10'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(null=True, upload_to='article/images', verbose_name='Изображение2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image3',
            field=models.ImageField(null=True, upload_to='article/images', verbose_name='Изображение3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image4',
            field=models.ImageField(null=True, upload_to='article/images', verbose_name='Изображение4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image5',
            field=models.ImageField(null=True, upload_to='article/images', verbose_name='Изображение5'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image6',
            field=models.ImageField(null=True, upload_to='article/images', verbose_name='Изображение6'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image7',
            field=models.ImageField(null=True, upload_to='article/images', verbose_name='Изображение7'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image8',
            field=models.ImageField(null=True, upload_to='article/images', verbose_name='Изображение8'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image9',
            field=models.ImageField(null=True, upload_to='article/images', verbose_name='Изображение9'),
        ),
    ]
